# Task



In [0]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [0]:
df = pd.read_excel ('/content/drive/My Drive/task/Data_Science_2020_v2.xlsx')

In [20]:
df.head()

Application_ID Current City  ...  Performance_12  Performance_10
0         DS0001    Bangalore  ...             NaN             NaN
1         DS0002       Mumbai  ...             NaN             NaN
2         DS0003       Mumbai  ...     91.40/91.40       9.40/9.40
3         DS0004      Dhanbad  ...     91.80/91.80     10.00/10.00
4         DS0005    Bangalore  ...             NaN             NaN

[5 rows x 14 columns]

# Observation
In the given task there is no need of stream and performance_PG,performance_UG,performance_12,performance_10 has nan in many cells

In [0]:
df.drop(['Application_ID','Current City','Institute','Stream','Performance_PG','Performance_UG','Performance_12','Performance_10'],axis=1,inplace=True)

In [0]:
df=df.rename(columns={"Python (out of 3)": "Python", "R Programming (out of 3)": "R","Data Science (out of 3)": "Data Science"})

# EDA

In [23]:
df.dtypes

Python                         int64
R                              int64
Data Science                   int64
Other skills                  object
Degree                        object
Current Year Of Graduation     int64
dtype: object

In [0]:
df.loc[df['Python'] == 3, ['Python']] = 10
df.loc[df['Python'] == 1, ['Python']] = 3
df.loc[df['Python'] == 2, ['Python']] = 7


df.loc[df['R'] == 3, ['R']] = 10
df.loc[df['R'] == 1, ['R']] = 3
df.loc[df['R'] == 2, ['R']] = 7

 
df.loc[df['Data Science'] == 3, ['Data Science']] = 10
df.loc[df['Data Science'] == 1, ['Data Science']] = 3
df.loc[df['Data Science'] == 2, ['Data Science']] = 7 

In [25]:
df

Python  R  ...                           Degree Current Year Of Graduation
0         3  0  ...    Bachelor of Engineering (B.E)                       2019
1         7  3  ...                              NaN                       2020
2         7  0  ...  Bachelor of Technology (B.Tech)                       2018
3         7  0  ...                Integrated M.Tech                       2021
4         7  0  ...    Bachelor of Engineering (B.E)                       2018
..      ... ..  ...                              ...                        ...
606       7  7  ...    Bachelor of Engineering (B.E)                       2020
607       3  0  ...       PG Diploma in Data Science                       2020
608       7  7  ...  Bachelor of Technology (B.Tech)                       2016
609      10  7  ...       Bachelor of Science (B.Sc)                       2018
610       7  7  ...    Master of Technology (M.Tech)                       2016

[611 rows x 6 columns]

In [26]:
df['Degree'].unique()

array(['Bachelor of Engineering (B.E)', nan,
       'Bachelor of Technology (B.Tech)', 'Integrated M.Tech',
       'B.Tech (Hons.)', 'Master of Business Administration_(MBA)', 'MBA',
       'Master of Science (M.Sc)', 'Post Graduate Programme (PGP)',
       'Master of Computer Applications (MCA)',
       'Bachelor of Pharmacy (B.Pharm)', 'Integrated MCA',
       'Bachelor of Commerce (B.Com)', 'Master of Technology (M.Tech)',
       'Integrated B.Sc. & M.Sc.', 'Post Graduate Diploma',
       'Integrated M.Sc.', 'Master of Arts (M.A.)',
       'PG Diploma in Data Science', 'Bachelor of Science (B.Sc)',
       'Integrated B.Tech', 'Master of Statistics (M.Stat)',
       'Post Graduate Diploma in Management (P.G.D.M.)',
       'Master of Engineering (M.E)', 'Master Of Analytics',
       'Bachelor of Computer Applications (BCA)',
       'Integrated B.S. & M.S.', 'Bachelor of Science (B.Sc) (Hons.)',
       'Bachelor of Computer Science (B.C.S.)',
       'Master of Science (M.S.)', 'Master 

In [0]:
df['degreescore']=0
df['skillscore']=0

In [0]:
#bachelor
df.loc[(df["Degree"] == "Bachelor of Engineering (B.E)") | (df["Degree"] == "Bachelor of Technology (B.Tech)") | (df["Degree"] == "B.Tech (Hons.)") | (df["Degree"] == "Bachelor of Engineering (B.E) (Hons.)") | (df["Degree"] == "Integrated B.Tech & M.Tech") | (df["Degree"] == "Integrated B.Tech & MBA") & (df["Current Year Of Graduation"] > 2020) , "degreescore"] += 0
df.loc[(df["Degree"] == "Bachelor of Engineering (B.E)") | (df["Degree"] == "Bachelor of Technology (B.Tech)") | (df["Degree"] == "B.Tech (Hons.)") | (df["Degree"] == "Bachelor of Engineering (B.E) (Hons.)") | (df["Degree"] == "Integrated B.Tech & M.Tech") | (df["Degree"] == "Integrated B.Tech & MBA") & (df["Current Year Of Graduation"] == 2020) , "degreescore"] += 10
df.loc[(df["Degree"] == "Bachelor of Engineering (B.E)") | (df["Degree"] == "Bachelor of Technology (B.Tech)") | (df["Degree"] == "B.Tech (Hons.)") | (df["Degree"] == "Bachelor of Engineering (B.E) (Hons.)") | (df["Degree"] == "Integrated B.Tech & M.Tech") | (df["Degree"] == "Integrated B.Tech & MBA") & (df["Current Year Of Graduation"] == 2019) , "degreescore"] += 8
df.loc[(df["Degree"] == "Bachelor of Engineering (B.E)") | (df["Degree"] == "Bachelor of Technology (B.Tech)") | (df["Degree"] == "B.Tech (Hons.)") | (df["Degree"] == "Bachelor of Engineering (B.E) (Hons.)") | (df["Degree"] == "Integrated B.Tech & M.Tech") | (df["Degree"] == "Integrated B.Tech & MBA") & (df["Current Year Of Graduation"] <= 2018) , "degreescore"] += 5
#masters
df.loc[(df["Degree"] == "Master of Science (M.Sc)") |  (df["Degree"] == "Master of Technology (M.Tech)")| (df["Degree"] == "Integrated B.Sc. & M.Sc.")| (df["Degree"] == "Integrated M.Sc.")| (df["Degree"] == "Master of Science (M.S.)")| (df["Degree"] == "Master of Science (M.Sc) (Hons.)")| (df["Degree"] == "Integrated B.Tech & M.Tech") & (df["Current Year Of Graduation"] > 2020) , "degreescore"] += 0
df.loc[(df["Degree"] == "Master of Science (M.Sc)") |  (df["Degree"] == "Master of Technology (M.Tech)")| (df["Degree"] == "Integrated B.Sc. & M.Sc.")| (df["Degree"] == "Integrated M.Sc.")| (df["Degree"] == "Master of Science (M.S.)")| (df["Degree"] == "Master of Science (M.Sc) (Hons.)")| (df["Degree"] == "Integrated B.Tech & M.Tech") & (df["Current Year Of Graduation"] == 2020) , "degreescore"] += 7
df.loc[(df["Degree"] == "Master of Science (M.Sc)") |  (df["Degree"] == "Master of Technology (M.Tech)")| (df["Degree"] == "Integrated B.Sc. & M.Sc.")| (df["Degree"] == "Integrated M.Sc.")| (df["Degree"] == "Master of Science (M.S.)")| (df["Degree"] == "Master of Science (M.Sc) (Hons.)")| (df["Degree"] == "Integrated B.Tech & M.Tech") & (df["Current Year Of Graduation"] <= 2019) , "degreescore"] += 3


In [29]:
df.loc[(df['Other skills'].str.contains('Machine Learning',na=False)),"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('Deep Learning',na=False)),"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('Natural Language Processing (NLP)',na=False)),"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('Data Analytics',na=False)),"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('Amazon Web Services (AWS)',na=False)),"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('SQL',na=False)) | (df['Other skills'].str.contains('MySQL',na=False)) ,"skillscore"] += 3
df.loc[(df['Other skills'].str.contains('MS-Excel',na=False)) | (df['Other skills'].str.contains('MS-Office',na=False)) ,"skillscore"] += 3


/usr/local/lib/python3.6/dist-packages/pandas/core/strings.py:1843: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)


In [0]:
df

In [0]:
df.drop(['Other skills','Degree','Current Year Of Graduation'],axis=1,inplace=True)

In [0]:
df['total']=df['Python']+df['R']+df['Data Science']+df['degreescore']+df['skillscore']

In [0]:
df['lable']=0
df.loc[(df["total"] >= 40),'lable']=1 
df.drop(['total'],axis=1,inplace=True)     

In [0]:
y_true=df['lable']

In [149]:
df

Python  R  Data Science  degreescore  skillscore  lable
0         3  0            10           23           9      1
1         7  3             7            0          12      0
2         7  0             0           23           0      0
3         7  0             7            0           9      0
4         7  0             0           23           6      0
..      ... ..           ...          ...         ...    ...
606       7  7             7           23          12      1
607       3  0             0            0           6      0
608       7  7             0           23           9      1
609      10  7             7            0          15      0
610       7  7             0           10           9      0

[611 rows x 6 columns]

The final data set

In [0]:
y=np.array(df['lable'])
x=np.array(df.drop(['lable'],axis=1))

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

# Logistic Regression

In [139]:
import warnings
warnings.filterwarnings("ignore")
tuned_parameters = [{'C': [10**-4, 10**-2, 10**0, 10**2, 10**4],'penalty': ['l1', 'l2'],'max_iter':[10,20,30,40,50,60]}]
model = GridSearchCV(LogisticRegression(), tuned_parameters, scoring = 'accuracy', cv=5)
model.fit(X_train, y_train)

print(model.best_estimator_)
print(model.score(X_test, y_test))

LogisticRegression(C=10000, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=40,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
0.9891304347826086


In [0]:
lr = LogisticRegression(C=10000, class_weight=None, dual=False, fit_intercept=True,
                        intercept_scaling=1, l1_ratio=None, max_iter=40,
                        multi_class='auto', n_jobs=None, penalty='l2',
                        random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                        warm_start=False)
lr.fit(X_train, y_train)
Y_pred = lr.predict(X_test)

In [142]:
lracc=lr.score(X_test, y_test)
lracc

0.9891304347826086

In [143]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[124,   0],
       [  2,  58]])

# SVM

In [132]:
param_grid = {'C': [0.1, 1, 10, 100, 1000],  
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001], 
              'kernel': ['rbf']} 
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 
grid.fit(X_train, y_train) 
print(grid.best_estimator_)  

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.733, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.709, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.776, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.776, total=   0.0s
[CV] C=0.1, gamma=1, kernel=rbf ......................................
[CV] .......... C=0.1, gamma=1, kernel=rbf, score=0.776, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C=0.1, gamma=0.1, kernel=rbf, score=0.779, total=   0.0s
[CV] C=0.1, gamma=0.1, kernel=rbf ....................................
[CV] ........ C

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV] ........ C=1, gamma=0.001, kernel=rbf, score=0.976, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.837, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.860, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.965, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.929, total=   0.0s
[CV] C=1, gamma=0.0001, kernel=rbf ...................................
[CV] ....... C=1, gamma=0.0001, kernel=rbf, score=0.871, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] ........... C=10, gamma=1, kernel=rbf, score=0.907, total=   0.0s
[CV] C=10, gamma=1, kernel=rbf .......................................
[CV] .

[Parallel(n_jobs=1)]: Done 125 out of 125 | elapsed:    0.5s finished


In [133]:
svm = SVC(C=1000, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
svm.fit(X_train, y_train)
Y_pred = svm.predict(X_test)
svmacc = svm.score(X_test, y_test)
svmacc

0.9836956521739131

In [134]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[123,   1],
       [  2,  58]])

# KNN

In [84]:
from sklearn.model_selection import GridSearchCV
alphas =[1,2,3,4,5, 10, 15, 21, 31, 41, 51]

param_grid = {'n_neighbors':alphas}
grid = GridSearchCV(estimator = knn,param_grid=param_grid ,scoring = 'accuracy')
grid.fit(X_train, y_train)


print(grid.best_estimator_)
print(grid.score(X_test, y_test))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')
0.9891304347826086


In [85]:
knn = KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')
knn.fit(X_train, y_train)
Y_pred = knn.predict(X_test)
knnacc = knn.score(X_test, y_test)
knnacc

0.9891304347826086

In [86]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[123,   1],
       [  1,  59]])

# Naive Bayes

In [87]:
nb = GaussianNB()
nb.fit(X_train, y_train)
Y_pred = nb.predict(X_test)
nbacc = nb.score(X_test, y_test)
nbacc

0.9510869565217391

In [68]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[121,   3],
       [  6,  54]])

# Decision Tree

In [128]:
#n_components = list(range(1,X_train.shape[1]+1,1))
criterion = ['gini', 'entropy']
max_depth = [4,6,8,12]
parameter = { 'criterion':criterion,'max_depth':max_depth}
dt = DecisionTreeClassifier()
clf = GridSearchCV(dt, parameter)

clf.fit(X_train, y_train)

print(clf.best_estimator_.get_params())


{'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': 8, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'presort': 'deprecated', 'random_state': None, 'splitter': 'best'}


In [0]:
alphas =[10**-4, 10**-3,10**-2,10**-1,10**0,10,10**2,10**3,10**4]

param_grid = {'alpha':alphas}
grid = GridSearchCV(estimator = sgd,param_grid=param_grid ,scoring = 'roc_auc')
grid.fit(X_train_tfidf, y_train)


print(clf.best_estimator_.get_params()['decisiontree'])


In [130]:
dt = DecisionTreeClassifier(ccp_alpha= 0.0, class_weight= None, criterion= 'gini', max_depth=8, max_features=None, max_leaf_nodes=None, min_impurity_decrease= 0.0, min_impurity_split= None, min_samples_leaf= 1, min_samples_split= 2, min_weight_fraction_leaf= 0.0, presort= 'deprecated', random_state= None, splitter= 'best')
dt.fit(X_train, y_train)
Y_pred = dt.predict(X_test)
dtacc = dt.score(X_test, y_test)
dtacc

0.9836956521739131

In [131]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[124,   0],
       [  3,  57]])

# Random Forest

In [0]:
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold

In [0]:
max_depth=[1, 5, 10, 50, 100, 500, 1000]
n_estimators =[5, 10, 100, 500]
max_features =[3, 5, 10, 20]
min_samples_split =[3, 5, 10]


In [120]:
from sklearn.model_selection import GridSearchCV
clf = RandomForestClassifier(random_state=0)
parameter = {'n_estimators':n_estimators, 'max_depth':max_depth,'max_features':max_features,'min_samples_split':min_samples_split}
clf = GridSearchCV(RandomForestClassifier(),parameter,verbose=1,scoring='accuracy',n_jobs=-1)
clf.fit(X_train,y_train)
estimator_opt, depth_opt,features_opt,samples_split_opt = clf.best_params_.get('n_estimators'), clf.best_params_.get('max_depth'),clf.best_params_.get('max_features'),clf.best_params_.get('min_samples_split')


Fitting 5 folds for each of 336 candidates, totalling 1680 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  80 tasks      | elapsed:   14.3s
[Parallel(n_jobs=-1)]: Done 322 tasks      | elapsed:   43.4s
[Parallel(n_jobs=-1)]: Done 820 tasks      | elapsed:  1.8min
[Parallel(n_jobs=-1)]: Done 1510 tasks      | elapsed:  3.1min
[Parallel(n_jobs=-1)]: Done 1680 out of 1680 | elapsed:  3.4min finished


In [121]:
print("The optimal value of n_estimator = ", estimator_opt , " And max_depth is : ", depth_opt," And max_features is : ", features_opt," And min_samples_split is : ", samples_split_opt)

The optimal value of n_estimator =  500  And max_depth is :  100  And max_features is :  5  And min_samples_split is :  3


In [146]:
rf = RandomForestClassifier(n_estimators=5,max_depth=500,min_samples_split=3,max_features=5)
rf.fit(X_train, y_train)
Y_pred = rf.predict(X_test)
rfacc = rf.score(X_train, y_train)
rfacc

0.9953161592505855

In [123]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,Y_pred)

array([[124,   0],
       [  4,  56]])

In [144]:
from prettytable import PrettyTable
print("BOW and TFIDF without Feature engineering")   
a = PrettyTable()

a.field_names = ["Model","Accuracy"]

a.add_row(["Logistic Regression", 0.9891])
a.add_row(["SVM",0.9836])
a.add_row(["KNN",0.9891])
a.add_row(["Naive Bayes",0.9510])
a.add_row(["Decision Tree",0.9836])
a.add_row(["Random Forest",0.9906])
print(a)

BOW and TFIDF without Feature engineering
+---------------------+----------+
|        Model        | Accuracy |
+---------------------+----------+
| Logistic Regression |  0.9891  |
|         SVM         |  0.9836  |
|         KNN         |  0.9891  |
|     Naive Bayes     |  0.951   |
|    Decision Tree    |  0.9836  |
|    Random Forest    |  0.9906  |
+---------------------+----------+


# Observation:
Random forest is the best model 

# Evaluation

In [0]:
df = pd.read_excel ('/content/drive/My Drive/task/Data_Science_2020_v2.xlsx')

In [0]:
Y_pred=rf.predict(x)

In [0]:
Y_pred

In [0]:
df['True_Y']=y_true
df['pred_Y']=Y_pred

In [0]:
df.to_csv('taskresults.csv',index=False)
from google.colab import files
files.download('taskresults.csv')